"""Initial migration.

Revision ID: dddc0599d4d7
Revises: 0d8191295209
Create Date: 2024-11-26 15:02:45.354740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddc0599d4d7'
down_revision = '0d8191295209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ProfilePicture', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ProfilePicture')

    # ### end Alembic commands ###
