"""Initial migration.

Revision ID: f98d5a0f3860
Revises: 
Create Date: 2024-11-20 09:12:20.143933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98d5a0f3860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PhoneNumber', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('IsPublic', sa.Boolean(), server_default=sa.text('(false)'), nullable=False))
        batch_op.create_unique_constraint("uq_user_phone_number", ['PhoneNumber'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('IsPublic')
        batch_op.drop_column('PhoneNumber')

    # ### end Alembic commands ###
